# Generated by Django 2.2.1 on 2019-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('user_id', models.IntegerField(blank=True)),
                ('listing_id', models.IntegerField()),
                ('realtor_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
