version: "2"
checks:
  method-lines:
    config:
      threshold: 90
  similar-code:
    enabled: false
  identical-code:
    enabled: false

exclude_patterns:
  - "templates/*"
  - "static/*"
  - "media/*"
  - "*/migrations/*"
  - "staticfiles/*"
  - "trulyestate/static/*"
