# Generated by Django 2.2.1 on 2019-06-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('list_date', models.DateTimeField(auto_now_add=True)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y%m/%d/')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
